name: .NET

on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${{ github.ref_name }}
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${{ github.ref_name }}
    - name: Push
      run: dotnet nuget push **\*.${{ github.ref_name }}.nupkg --source https://nuget.pkg.github.com/Fornari-Simone/index.json --api-key ${TOKEN} --skip-duplicate
      env:
        TOKEN: ${{ secrets.TOKEN }}
